1. Write a NumPy program to print the NumPy version in your system

In [1]:
!pip install numpy
import numpy as np



You should consider upgrading via the 'e:\program_file\python\python.exe -m pip install --upgrade pip' command.


In [2]:
np.__version__ 

'1.19.3'

2. Write a NumPy program to convert a list of numeric value into a one-dimensional 
NumPy array. Go to the editor
Expected Output:

    Original List: [12.23, 13.32, 100, 36.32]

In [3]:
list_01 = [12.23,13.32,100,36.32]
array_01 = np.array(list_01)
print(array_01)

[ 12.23  13.32 100.    36.32]


3. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10. 
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]

In [4]:
array_02 = np.arange(2,11)
array_02=array_02.reshape(3,3)
print(array_02)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


4. Write a NumPy program to create a null vector of size 10 and update sixth value 
to 11.

[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11

[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [5]:
#crearting null value array
array_01 = np.zeros((10))
print(array_01)

#swaping the sixth position value
array_01[6]= 11
print(array_01)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


5. Write a NumPy program to reverse an array (first element becomes last).

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 
37]

Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 
12

In [6]:
original_array = np.arange(12,38)
print(original_array)

reverse_array = np.flip(original_array)
print('\n',reverse_array)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]

 [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


6. Write a NumPy program to convert an array to a float type. 

Sample output:
Original array
[1, 2, 3, 4]


Array converted to a float type:
[ 1. 2. 3. 4.]

In [7]:
int_array = np.arange(1,5)
print(int_array)
float_array = int_array.astype(np.float)
print(float_array)

[1 2 3 4]
[1. 2. 3. 4.]


7. Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 
Expected Output:
    
[[ 1. 1. 1. 1. 1.] 

[ 1. 0. 0. 0. 1.] 

[ 1. 0. 0. 0. 1.] 

[ 1. 0. 0. 0. 1.] 

[ 1. 1. 1. 1. 1.]]


In [8]:
row_01 = np.array([[1,1,1,1,1],[1,0,0,0,1]])
row_02 = np.flip(row_01)
print(np.concatenate((row_01,row_02),axis=0).astype(float))


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


8. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard 
pattern.

Checkerboard pattern:

[[0 1 0 1 0 1 0 1] 
 
[1 0 1 0 1 0 1 0] 
 
[0 1 0 1 0 1 0 1] 
 
[1 0 1 0 1 0 1 0] 
 
[0 1 0 1 0 1 0 1] 
 
[1 0 1 0 1 0 1 0] 
 
[0 1 0 1 0 1 0 1] 
 
[1 0 1 0 1 0 1 0]]

In [9]:
array = np.ones((8,8))
array = array.astype(int)
print(array)

for i in range(0,8):
    for j in range(0,8,2):
        if(i%2==0):
            array[i][j]=0
        else:
            array[i][j+1]=0
array
    
    


[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

9. Write a NumPy program to convert the values of Centigrade degrees into 
Fahrenheit degrees. Centigrade values are stored into a NumPy array. 

Sample Array [0, 12, 45.21 ,34, 99.91]

Expected Output:
    
Values in Fahrenheit degrees:
    
[ 0. 12. 45.21 34. 99.91]

Values in Centigrade degrees:
    
[-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [10]:
celsius = np.array([0,12,45.21,34,99,91])
print("celsius:",celsius)
fahrenheit = celsius * (9/5) +32
print("fahrenheit:",fahrenheit)
print("\n")
celsius = np.array([-17.77777778, -11.11111111, 7.33888889, 1.11111111, 37.72777778])
print("celsius:",celsius)
fahrenheit = celsius * (9/5) + 32
print("fahrenheit",fahrenheit)

celsius: [ 0.   12.   45.21 34.   99.   91.  ]
fahrenheit: [ 32.     53.6   113.378  93.2   210.2   195.8  ]


celsius: [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]
fahrenheit [-4.00000033e-09  1.20000000e+01  4.52100000e+01  3.40000000e+01
  9.99100000e+01]


10. Write a NumPy program to find common values between two arrays. 
Expected Output:
    
Array1: [ 0 10 20 40 60]
    
Array2: [10, 30, 40]
    
Common values between two arrays:
    
[10 40]

In [11]:
array_01 = np.array([0,10,20,40,60])
array_02 = np.array([10,30,40])

for i in array_01:
    for j in array_02:
        if(i==j):
            print(j)


10
40


11. Write a NumPy program to get the unique elements of an array. 
Expected Output:
Original array:

[10 10 20 20 30 30]

Unique elements of the above array:

[10 20 30]

Original array:

[[1 1]

[2 3]]

Unique elements of the above array:

[1 2 3]

In [12]:
input_array = np.array([10,10,20,20,30,30])
unique_array=np.unique(input_array)
print(unique_array)

input_array = np.array([[1,1],[2,3]])
unique_array = np.unique(input_array)
print(unique_array)

[10 20 30]
[1 2 3]


12.Write a NumPy program to find the indices of the maximum and minimum values 
along the given axis of an array.
Original array: [1 2 3 4 5 6]
Maximum Values: 5
Minimum Values: 0

In [13]:
array = np.array([1,2,3,4,5,6])
print(array.argmax())
print(array.argmin())

5
0


13.Write a NumPy program to create a new shape to an array without changing its 
data. 
Reshape 3x2:
[[1 2]
[3 4]
[5 6]]
Reshape 2x3:
[[1 2 3]
[4 5 6]]


In [14]:
array = np.array([[1,2],[3,4],[5,6]])
print(array.reshape(2,3))

[[1 2 3]
 [4 5 6]]


14.Write a NumPy program to create a 1-D array going from 0 to 50 and an array 
from 10 to 50. 
Expected Output:
Array from 0 to 50:
[ 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Array from 10 to 50:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

In [15]:
array_01 = np.arange(0,50)
array_02 = np.arange(10,50)
print(array_01)
print(array_02)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


15.Write a NumPy program to Create a 1-D array of 30 evenly spaced elements 
between 2.5. and 6.5, inclusive. 
Expected Output:
[ 2.5 2.63793103 2.77586207 2.9137931 3.05172414 3.18965517
.................
5.81034483 5.94827586 6.0862069 6.22413793 6.36206897 6.5 ]


In [16]:
array = np.linspace(2.5,6.5,30)
print(array)

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


16.Write a NumPy program to create an array which looks like below array.
[[ 0. 0. 0.] 
[ 1. 0. 0.] 
[ 1. 1. 0.] 
[ 1. 1. 1.]]

In [17]:
array = np.zeros((4,3))
array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

17.Write a NumPy program to interchange two axes of an array. 
Sample array: [[1 2 3]]
Expected Output:
[[1]
[2]
[3]]

In [18]:
array = np.array([[1,2,3]])
print(array)
array = np.swapaxes(array,0,1) #parameter: array,first axis, second axis
print(array)


[[1 2 3]]
[[1]
 [2]
 [3]]


18.Write a NumPy program to swap columns in a given array. 
Sample Output:
Original array:
    [[ 0 1 2 3]
    [ 4 5 6 7]
    [ 8 9 10 11]]
After swapping arrays:
    [[ 1 0 2 3]
    [ 5 4 6 7]
    [ 9 8 10 11]]


In [19]:
array = np.arange(0,12).reshape(3,4)
print(array)

array[:,[0,1]]=array[:,[1,0]] #slicing the array
print(array)
    

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  0  2  3]
 [ 5  4  6  7]
 [ 9  8 10 11]]


19.Replace all odd numbers in arr with -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array([ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1])


In [20]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)
odd_num = np.argwhere((arr%2==1)).flatten() #converts 2D into 1D
arr[odd_num] = -1
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


20.Create the following pattern without hardcoding. Use only numpy functions and 
the below input array a.
Input:
a = np.array([1,2,3])
Desired Output:
array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [21]:
a = np.array([1,2,3])
pattern_01= a.repeat(3)
pattern_02  = np.tile(a,3)
a = np.concatenate((pattern_01,pattern_02),axis=0)
print(a)



[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


21.Pretty print by suppressing the scientific notation (like 1e10)
Input: 
array([[ 5.434049e-04, 2.783694e-04, 4.245176e-04],
 [ 8.447761e-04, 4.718856e-06, 1.215691e-04],
 [ 6.707491e-04, 8.258528e-04, 1.367066e-04]])
Desired Output:
array([[ 0.000543, 0.000278, 0.000425],
 [ 0.000845, 0.000005, 0.000122],
 [ 0.000671, 0.000826, 0.000137]])

In [22]:
a=np.array([[5.434049e-04, 2.783694e-04, 4.245176e-04],[ 8.447761e-04, 4.718856e-06, 1.215691e-04],
[ 6.707491e-04, 8.258528e-04, 1.367066e-04]])
np.set_printoptions(suppress=True)
a

array([[0.0005434 , 0.00027837, 0.00042452],
       [0.00084478, 0.00000472, 0.00012157],
       [0.00067075, 0.00082585, 0.00013671]])

22.Provide NumPy code that calculates and prints each of the quantities below.

B = 1 2 -3   A = 2 -5 1   y= 2  z = -15
    3 4 -1       1  4 5     -4       -8
                 2 -1 6      1      -22
• BA
• ABT
• Ay
• yTz (This is the inner product, or dot product, of y and z.)
• yzT
(This is the outer product of y and z.

In [23]:
A = np.array([[2,-5,1],[1,4,5],[2,-1,6]])
B = np.array([[1,2,-3],[3,4,-1]])
y = np.array([[2],[-4],[1]])
z = np.array([[-15],[-8],[-22]])

In [24]:
#print BA
print(np.matmul(B,A))

[[-2  6 -7]
 [ 8  2 17]]


In [25]:
#print AB^T
B_transpose = B.transpose()
#print(B_transpose)
print(np.matmul(A,B_transpose))

[[-11 -15]
 [ -6  14]
 [-18  -4]]


In [26]:
#print Ay
print(np.matmul(A,y))

[[25]
 [-9]
 [14]]


In [27]:
#print y^tz
y_transpose = y.transpose()
print(np.matmul(y_transpose,z))

[[-20]]


In [28]:
#print yzT
z_transpose = z.transpose()
print(np.matmul(y,z_transpose))

[[-30 -16 -44]
 [ 60  32  88]
 [-15  -8 -22]]


23.How to get all the dates corresponding to the month of July 2016?
Expected output:
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
'2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
'2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
'2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
'2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
'2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
'2016-07-31']


In [29]:
days = np.arange('2016-07','2016-08',dtype='datetime64[D]')
days

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

24.How to get the dates of yesterday, today and tomorrow using NumPy?

In [30]:
#yesterday
print(np.datetime64('today')-1)
#today
print(np.datetime64('today'))
#tomorrow
print(np.datetime64('today')+1)


2021-06-24
2021-06-25
2021-06-26


25.Normalize a 5x5 random matrix.

In [31]:
array = np.random.randint(100,size=[5,5])
norm = np.linalg.norm(array)
normalized_array = array/norm
print(normalized_array)

[[0.15061386 0.14433828 0.08472029 0.26043646 0.2761254 ]
 [0.30122771 0.30750329 0.06275577 0.17885395 0.30122771]
 [0.24160973 0.17257838 0.19140511 0.         0.0282401 ]
 [0.06589356 0.13492491 0.14120049 0.31064108 0.19140511]
 [0.3043655  0.22905857 0.16944059 0.13492491 0.00627558]]
