In [2]:
!pip install numpy


You should consider upgrading via the 'e:\program_file\python\python.exe -m pip install --upgrade pip' command.


In [3]:
import numpy as np

In [4]:
array01 = np.array([1,2,3,4,5])
print(array01)
print(array01.shape) #shape
print(array01.dtype) #datatype
print(array01.size) #size
print(array01.ndim) #dimension
print(array01.itemsize) #size of array in bit

[1 2 3 4 5]
(5,)
int32
5
1
4


In [5]:
array02 = np.array([12,6,1,4,11])
print(array02[2])

1


In [6]:
array02[2] = 15 #editing the element of the array
print(array02[2])

15


In [7]:
#array vs list
l = [1,2,3,4,5] #this is list
a = np.array([1,2,3,4,5]) #this is array
print(a)
print(l)


[1 2 3 4 5]
[1, 2, 3, 4, 5]


In [8]:

l.append(6) #adding element to the list
print(l)

l2 = l + [10] #adding to the list
print(l2)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 10]


In [33]:
#broadcasting 
print(a)
a= a + np.array([1])
a

[1 2 3 4 5 6]


array([2, 3, 4, 5, 6, 7])

In [10]:
#adding to the array
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
newArray = np.append(a,b) #same as below
newArray = np.append(newArray,[12,31,2]) #this also work
newArray

array([ 1,  2,  3,  4,  1,  2,  3,  4, 12, 31,  2])

In [11]:
l = [1,2,3,4,5]
a = np.array([1,2,3,4,5])

l2 = l*2
print(l2)

a2 = a*2
print(a2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [12]:
print(l)
l3=[]
for i in l:
    l3.append(i**3) #power of i 
print(l3)


l4 = [i**3 for i in l] #same as above
print(l4)

[1, 2, 3, 4, 5]
[1, 8, 27, 64, 125]
[1, 8, 27, 64, 125]


In [13]:
a3 = np.sqrt(a) #square root
print(a3)
a3=np.log(a) #log
print(a3)
a3=np.exp(a) #expon
print(a3)

[1.         1.41421356 1.73205081 2.         2.23606798]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [14]:
a = np.array([3,5,6,7])
b = np.array([8,9,10,11])

dot = 0
for i in range(len(a)):
    dot+=a[i]*b[i]
print(dot)


numpy_dot = np.dot(a,b)
print(numpy_dot)

dot1 = a @ b
print(dot1)

206
206
206


In [15]:
from timeit import default_timer as timer
a = np.random.randn(1000) #random number generate
b = np.random.randn(1000)

A = list(a) #converting array into list
B = list(b)

T= 1000

#first method
def dot1():
    dot=0
    for i in range(len(a)):
        dot +=A[i] * B[i]
    return dot
#second method
def dot2():
    return np.dot(a,b)

#first timer
start = timer()
for t in range(T):
    dot1()
end=timer()
t1 = end-start

#second timer
start = timer()
for t in range(T):
    dot2()
end=timer()
t2 = end-start

print('TIme while using List:',t1)
print('TIme while using array:',t2)
print('Ratio:',t1/t2)

TIme while using List: 0.38516009999966627
TIme while using array: 0.027636400000119465
Ratio: 13.936695806906881


In [16]:
# two dimension array
# 1 2 3 4
# 5 6 7 8
a = np.array([[1,2,3,4],[5,6,7,8]]) 
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [17]:
print(a[0]) # first row of a
print(a[1]) # second row of a
print(a[0][0]) #accessing the first element
print(a[1,2]) #accesing the particular element; same as above

[1 2 3 4]
[5 6 7 8]
1
7


# slicing 


In [18]:
q = np.array([1,2,3,4,5,6,7,8])
print(q[1:4])
print('last three:',q[-3:])

a = np.array([[1,2,3,4],[5,6,7,8]]) 
print(a[:,0]) #accesing the first element of both row
print(a[0,:2])
print(a[:,-2:])

[2 3 4]
last three: [6 7 8]
[1 5]
[1 2]
[[3 4]
 [7 8]]


In [19]:
#concatenating 
a = np.array([[1,2],[3,4]])
print("Array A:",a)
b= np.array([[5,6],[7,8]])
print("Array B:",b)

c = np.concatenate((a,b),axis= None) #concatinating into single array
print('Axis None:',c)
d = np.concatenate((a,b),axis= 1) 
print('Axis 1:',d)
e = np.concatenate((a,b),axis= 0) 
print('Axis 0:',e)


#stacking
x = np.hstack((a,b))
print('X:',x)

y = np.vstack((a,b))
print('Y:',b)

Array A: [[1 2]
 [3 4]]
Array B: [[5 6]
 [7 8]]
Axis None: [1 2 3 4 5 6 7 8]
Axis 1: [[1 2 5 6]
 [3 4 7 8]]
Axis 0: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
X: [[1 2 5 6]
 [3 4 7 8]]
Y: [[5 6]
 [7 8]]


In [20]:
a = np.array([[1,2,3],[2,5,2]])
print(a.sum()) #aading all the element
print(a.sum(axis=0)) #adding according to the column
print(a.sum(axis=1)) #adding according to the row

15
[3 7 5]
[6 9]


In [21]:
print(a.mean()) #aading all the element
print(a.mean(axis=0)) #adding according to the column
print(a.mean(axis=1)) #adding according to the row

2.5
[1.5 3.5 2.5]
[2. 3.]


In [22]:
print(a.std()) #aading all the element
print(a.std(axis=0)) #adding according to the column
print(a.std(axis=1)) #adding according to the row

1.2583057392117916
[0.5 1.5 0.5]
[0.81649658 1.41421356]


In [23]:
print(a.max()) #aading all the element
print(a.max(axis=0)) #adding according to the column
print(a.max(axis=1)) #adding according to the row

5
[2 5 3]
[3 5]


In [24]:
a.dtype

dtype('int32')

In [25]:
#this is not the way to copy array
a = np.array([1,2,3,4])
b = a #referencing
b[0]=5
print(a)
print('Reference B:',b)

a = np.array([1,2,3,4])
b= a.copy()
print('New B:',b)

[5 2 3 4]
Reference B: [5 2 3 4]
New B: [1 2 3 4]


# EDA02 

In [26]:
#generating data
a = np.zeros((2,3)) #tuple - (x,y)
print('A:\n',a)

#generating ones value
b= np.ones((3,3))
print('B:\n',b)

#generating ones value multiply by 4
c= 4 * np.ones((3,3))
print("C:(ones multiply by 4\n)",c)

#same as c
d= np.full((3,3),5)
print('D:\n',d)

#identiy matrix
e = np.eye(2)
print('E:\n',e)

A:
 [[0. 0. 0.]
 [0. 0. 0.]]
B:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
C:(ones multiply by 4
) [[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
D:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
E:
 [[1. 0.]
 [0. 1.]]


# Range

In [27]:
#range of number
f = np.arange(10)
print('F:\n',f)

g =np.arange(1,6,2) #starting from 1 to range 6 with 2 step gap
print('g:\n',g)

h= np.linspace(0,16,2) #generating equal spacing number 
print('h:\n',h)

F:
 [0 1 2 3 4 5 6 7 8 9]
g:
 [1 3 5]
h:
 [ 0. 16.]


In [28]:
#random number generate
a = np.random.random((3,2))
print("a:",a)

b= np.random.randn(3,2)
print('b:',b)

#always equally divided so mean is always zero and std and var is always 1
c = np.random.randn(50)
# print("C:",c)
# print("Mean",c.mean())
# print("Variance",c.var())
# print("Standard Deviance",c.std())

#genertate integer number from 1 to some range
d= np.random.randint(3,10,size = (3,3))
print("D:",d)

#generate array *1D
e= np.random.randint(20, size=(5))
print('E:',e)

#generate random number from the choice 
f=np.random.choice([1,2,3,4,5,12,60],size =8)
print('f:',f)

a: [[0.98607309 0.67784744]
 [0.36012625 0.3223694 ]
 [0.0726968  0.22562771]]
b: [[-0.06290886  0.80248721]
 [-0.40739926  1.0283821 ]
 [-0.89817717  1.26465298]]
D: [[3 8 8]
 [8 9 9]
 [4 9 4]]
E: [15  7 14 13 17]
f: [ 4 60  1  4  3  2  2  3]


In [29]:
#search number or filter number in an array
a = np.array([[1,2],[3,4],[4,5]])
print("A",a)


bool_index = a>2
# print(bool_index)
# print(a[bool_index])

#smae as above but shorter
print("Filtered:",a[a>3])

#replace number
search = np.where(a>2,a,5)
print("Replace:",search)

A [[1 2]
 [3 4]
 [4 5]]
Filtered: [4 4 5]
Replace: [[5 5]
 [3 4]
 [4 5]]


In [30]:
#fancy selection 
p = np.array ([1,2,3,4,5,7,6])
q= [1,2,3,4]
print(p[q])

#selecting odd or even number ; it return index of even number
even=np.argwhere((p%2==0).flatten()) #flatten converts 2D array into 1D array
print('even index:',even)
print("Even number:",p[even])

odd=np.argwhere((p%2==1).flatten()) #flatten converts 2D array into 1D array
print('odd index:',odd)
print("odd number:",p[odd])

[2 3 4 5]
even index: [[1]
 [3]
 [6]]
Even number: [[2]
 [4]
 [6]]
odd index: [[0]
 [2]
 [4]
 [5]]
odd number: [[1]
 [3]
 [5]
 [7]]


In [31]:
p = np.array([3,6,7,1,3,5,12,3])
print("P:",p)

#give index of smallest and highest number index
print("largest value index:",p.argmax())
print("smallest value index:",p.argmin())

print("largest value:",p[p.argmax()])
print("smallest value:",p[p.argmin()])

P: [ 3  6  7  1  3  5 12  3]
largest value index: 6
smallest value index: 3
largest value: 12
smallest value: 1


In [32]:
a = np.arange(1,7)
print("a:",a)

#change 1D into 2D or can be converted into any dimension array
b=a.reshape(3,2)
print("reshaped:",b)

a: [1 2 3 4 5 6]
reshaped: [[1 2]
 [3 4]
 [5 6]]
